// words-7.js — 7-letter Australian English word list for Aussie Word Challenge

export const WORDS_7 = [
  { word: "abandon", definition: "To leave someone or something, especially in a difficult situation.", pronunciation: "uh-BAN-dun", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "ability", definition: "The skill or power to do something.", pronunciation: "uh-BIL-i-tee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "absence", definition: "The state of being away from a place or person.", pronunciation: "AB-suns", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "account", definition: "A record of money paid in or out; to give a description.", pronunciation: "uh-KOWNT", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "achieve", definition: "To successfully reach a goal by effort.", pronunciation: "uh-CHEEV", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "address", definition: "The details of where someone lives; to speak to a group.", pronunciation: "uh-DRES", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "advance", definition: "To move forward; to make progress.", pronunciation: "ad-VANS", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "against", definition: "In opposition to; in contact with.", pronunciation: "uh-GENST", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "already", definition: "Before the expected time; by now.", pronunciation: "awl-RED-ee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "ancient", definition: "Belonging to the very distant past.", pronunciation: "AYN-shunt", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "another", definition: "A different or further one of the same kind.", pronunciation: "uh-NUTH-er", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "anxiety", definition: "A feeling of worry and nervousness.", pronunciation: "ang-ZY-uh-tee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "anybody", definition: "Any person at all.", pronunciation: "EN-ee-bod-ee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "anxious", definition: "Feeling worried and nervous about something.", pronunciation: "ANGK-shus", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "arrange", definition: "To put things in a particular order; to make plans.", pronunciation: "uh-RAYNJ", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "attempt", definition: "To make an effort to do something.", pronunciation: "uh-TEMPT", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "attract", definition: "To cause someone to come towards you.", pronunciation: "uh-TRAKT", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "auction", definition: "A public sale where items go to whoever bids highest.", pronunciation: "AWK-shun", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "average", definition: "The result of adding numbers together and dividing by how many there are.", pronunciation: "AV-er-ij", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "awkward", definition: "Causing difficulty; uncomfortable; not graceful.", pronunciation: "AWK-werd", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "balance", definition: "A state where things are equal; to keep steady.", pronunciation: "BAL-uns", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "battery", definition: "A device that stores and provides electrical power.", pronunciation: "BAT-er-ee", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "because", definition: "For the reason that; since.", pronunciation: "bi-KOZ", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "bedrock", definition: "The solid rock under loose material; the basic principles.", pronunciation: "BED-rok", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "between", definition: "In the space separating two things.", pronunciation: "bi-TWEEN", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "bicycle", definition: "A vehicle with two wheels powered by pedalling.", pronunciation: "BY-si-kul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "blanket", definition: "A large piece of fabric used as a covering for warmth.", pronunciation: "BLANK-it", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "blossom", definition: "A flower on a tree; to develop in a healthy way.", pronunciation: "BLOS-um", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "brother", definition: "A male who has the same parents as you.", pronunciation: "BRUTH-er", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "buffalo", definition: "A large bovine animal found in Africa and Asia.", pronunciation: "BUF-uh-loh", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "cabinet", definition: "A cupboard with shelves; a group of senior government ministers.", pronunciation: "KAB-i-net", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "canteen", definition: "A place in a school or factory where meals are served.", pronunciation: "kan-TEEN", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "captain", definition: "The person in charge of a ship, aircraft or sports team.", pronunciation: "KAP-tin", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "capture", definition: "To catch something or someone and keep them held.", pronunciation: "KAP-cher", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "cartoon", definition: "An amusing drawing; an animated film.", pronunciation: "kar-TOON", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "central", definition: "In the middle of an area; most important.", pronunciation: "SEN-trul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "century", definition: "A period of one hundred years.", pronunciation: "SEN-chuh-ree", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "careful", definition: "Giving serious attention to avoid mistakes or danger.", pronunciation: "KAIR-ful", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "chapter", definition: "A section of a book; a period in a person's life.", pronunciation: "CHAP-ter", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "chicken", definition: "A common farm bird kept for its eggs and meat.", pronunciation: "CHIK-en", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "chimney", definition: "A vertical pipe that carries smoke up from a fire.", pronunciation: "CHIM-nee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "collect", definition: "To bring things together into one place.", pronunciation: "kuh-LEKT", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "combine", definition: "To join together to make a single thing.", pronunciation: "kum-BYN", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "comfort", definition: "A state of ease and freedom from pain; to make someone feel better.", pronunciation: "KUM-fert", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "command", definition: "An instruction that must be obeyed; to be in charge of.", pronunciation: "kuh-MAND", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "company", definition: "A business; a group of people spending time together.", pronunciation: "KUM-puh-nee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "concern", definition: "Worry or anxiety; to involve or affect someone.", pronunciation: "kun-SURN", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "connect", definition: "To join two things together.", pronunciation: "kuh-NEKT", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "contain", definition: "To have something inside; to prevent from spreading.", pronunciation: "kun-TAYN", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "contest", definition: "A competition; to challenge or dispute something.", pronunciation: "KON-test", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "control", definition: "The power to manage or determine what happens.", pronunciation: "kun-TROHL", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "council", definition: "A group of people elected to manage local government.", pronunciation: "KOWN-sul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "country", definition: "A nation with its own government; land outside cities.", pronunciation: "KUN-tree", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "courage", definition: "The ability to do something frightening; bravery.", pronunciation: "KUR-ij", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "curious", definition: "Eager to know or learn about something.", pronunciation: "KYOOR-ee-us", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "curtain", definition: "A hanging piece of fabric used to cover a window.", pronunciation: "KUR-ten", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "cushion", definition: "A soft bag filled with material for sitting or leaning on.", pronunciation: "KUSH-un", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "dancing", definition: "Moving the body rhythmically to music.", pronunciation: "DAN-sing", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "darkest", definition: "The superlative of dark; having the least light.", pronunciation: "DAR-kest", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "declare", definition: "To state something officially and publicly.", pronunciation: "di-KLAIR", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "defence", definition: "The action of protecting from attack (Australian spelling).", pronunciation: "di-FENS", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "deserve", definition: "To be worthy of something because of your actions.", pronunciation: "di-ZURV", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "despite", definition: "Without being affected by something; in spite of.", pronunciation: "di-SPYT", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "devoted", definition: "Deeply committed and loyal to a person or cause.", pronunciation: "di-VOH-ted", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "digital", definition: "Relating to computer technology; using numbers to represent data.", pronunciation: "DIJ-i-tul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "dinning", definition: "Making a loud continuous noise.", pronunciation: "DIN-ing", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "disease", definition: "An illness affecting the body or mind.", pronunciation: "di-ZEEZ", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "distant", definition: "Far away in space or time.", pronunciation: "DIS-tunt", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "dolphin", definition: "An intelligent sea mammal that lives in groups.", pronunciation: "DOL-fin", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "dynamic", definition: "Characterised by constant change and energy.", pronunciation: "dy-NAM-ik", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "earlier", definition: "Before the usual or expected time.", pronunciation: "UR-lee-er", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "ecology", definition: "The study of how living things relate to each other and their environment.", pronunciation: "ee-KOL-uh-jee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "earring", definition: "A piece of jewellery worn on or through the ear.", pronunciation: "EER-ring", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "element", definition: "A part of something; a substance that cannot be broken down further.", pronunciation: "EL-uh-ment", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "embrace", definition: "To hold someone in your arms; to accept eagerly.", pronunciation: "em-BRAYS", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "empower", definition: "To give someone authority or strength to do something.", pronunciation: "em-POW-er", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "endorse", definition: "To publicly support or approve of something.", pronunciation: "en-DORS", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "energic", definition: "Having or showing great energy and activity.", pronunciation: "en-ER-jik", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "england", definition: "A country in the United Kingdom.", pronunciation: "ING-lund", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "enhance", definition: "To improve the quality or value of something.", pronunciation: "en-HANS", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "enquire", definition: "To ask for information about something (Australian spelling).", pronunciation: "en-KWYR", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "episode", definition: "One part of a series; an event in a sequence.", pronunciation: "EP-i-sohd", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "examine", definition: "To inspect something closely and carefully.", pronunciation: "eg-ZAM-in", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "excited", definition: "Feeling very happy and enthusiastic.", pronunciation: "ek-SY-ted", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "explore", definition: "To travel through a new area to find out about it.", pronunciation: "ek-SPLOR", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "express", definition: "To show feelings in words or actions; to travel quickly.", pronunciation: "ek-SPRES", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "factory", definition: "A building where goods are manufactured in large quantities.", pronunciation: "FAK-tuh-ree", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "failing", definition: "Not succeeding; a weakness in someone's character.", pronunciation: "FAYL-ing", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "feather", definition: "One of the light structures that covers a bird's body.", pronunciation: "FETH-er", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "feeling", definition: "An emotion; a physical sensation.", pronunciation: "FEEL-ing", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "ferment", definition: "To undergo a chemical change that produces bubbles or alcohol.", pronunciation: "fer-MENT", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "fiction", definition: "Literature that describes imaginary events and people.", pronunciation: "FIK-shun", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "fifteen", definition: "The number 15.", pronunciation: "fif-TEEN", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "filling", definition: "A substance used to fill a gap; the inside of food.", pronunciation: "FIL-ing", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "finance", definition: "The management of money; money used by a business.", pronunciation: "FY-nans", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "finding", definition: "The act of discovering something; a conclusion reached.", pronunciation: "FYN-ding", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "flatten", definition: "To make or become flat.", pronunciation: "FLAT-un", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "flavour", definition: "The taste of something (Australian spelling).", pronunciation: "FLAY-ver", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "flipper", definition: "A broad flat limb used for swimming.", pronunciation: "FLIP-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "flowing", definition: "Moving steadily and continuously.", pronunciation: "FLOH-ing", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "flyover", definition: "A bridge carrying one road over another.", pronunciation: "FLY-oh-ver", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "focused", definition: "Concentrating attention on one thing.", pronunciation: "FOH-kust", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "footbal", definition: "A game played with a ball on a field between two teams.", pronunciation: "FUT-bawl", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "forward", definition: "Towards the front; ahead in time.", pronunciation: "FOR-werd", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "freedom", definition: "The power to act, think or speak without restrictions.", pronunciation: "FREE-dum", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "freshly", definition: "In a fresh manner; recently.", pronunciation: "FRESH-lee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "general", definition: "Affecting or relating to all or most people; a senior military officer.", pronunciation: "JEN-er-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "getting", definition: "Obtaining or receiving something.", pronunciation: "GET-ing", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "glacier", definition: "A slowly moving mass of ice.", pronunciation: "GLAY-see-er", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "glimpse", definition: "A brief look at something.", pronunciation: "glimps", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "glitter", definition: "Tiny sparkling pieces; to shine with a bright flickering light.", pronunciation: "GLIT-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "gorilla", definition: "The largest of the great apes, found in African forests.", pronunciation: "guh-RIL-uh", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "grammar", definition: "The rules of a language relating to words and sentences.", pronunciation: "GRAM-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "granite", definition: "A very hard grey rock used in building.", pronunciation: "GRAN-it", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "gravity", definition: "The force that attracts objects towards the Earth.", pronunciation: "GRAV-i-tee", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "growing", definition: "Becoming larger or more developed.", pronunciation: "GROH-ing", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "habitat", definition: "The natural environment in which an animal or plant lives.", pronunciation: "HAB-i-tat", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "handful", definition: "An amount that can be held in one hand.", pronunciation: "HAND-ful", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "happily", definition: "In a happy and contented way.", pronunciation: "HAP-i-lee", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "harvest", definition: "The process of gathering crops; the crops gathered.", pronunciation: "HAR-vest", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "healthy", definition: "In good physical condition; promoting good health.", pronunciation: "HEL-thee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "hearing", definition: "The ability to perceive sound; a formal meeting.", pronunciation: "HEER-ing", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "helping", definition: "Giving assistance to someone.", pronunciation: "HEL-ping", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "highest", definition: "At the greatest height or level.", pronunciation: "HY-est", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "history", definition: "The study of past events; a past series of events.", pronunciation: "HIS-tuh-ree", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "holiday", definition: "A period of time when you are not working or studying.", pronunciation: "HOL-i-day", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "horizon", definition: "The line where the sky appears to meet the land or sea.", pronunciation: "huh-RY-zun", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "housing", definition: "Buildings where people live; the activity of providing homes.", pronunciation: "HOW-zing", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "however", definition: "Despite what has just been said; in whatever way.", pronunciation: "how-EV-er", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "hundred", definition: "The number 100.", pronunciation: "HUN-dred", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "hunting", definition: "The activity of catching wild animals for food or sport.", pronunciation: "HUN-ting", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "imagine", definition: "To form a picture of something in your mind.", pronunciation: "i-MAJ-in", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "improve", definition: "To make or become better.", pronunciation: "im-PROOV", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "include", definition: "To have or contain something as part of a whole.", pronunciation: "in-KLOOD", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "instead", definition: "As an alternative; in place of something.", pronunciation: "in-STED", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "involve", definition: "To include or affect something or someone.", pronunciation: "in-VOLV", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "inwards", definition: "Towards the inside or centre.", pronunciation: "IN-werdz", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "journey", definition: "A long trip from one place to another.", pronunciation: "JUR-nee", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "judging", definition: "Forming an opinion about something; making a decision.", pronunciation: "JUJ-ing", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "keeping", definition: "Continuing to have something; maintaining.", pronunciation: "KEEP-ing", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "kingdom", definition: "A country ruled by a king or queen.", pronunciation: "KING-dum", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "kitchen", definition: "The room in a house where food is prepared and cooked.", pronunciation: "KICH-un", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "knowing", definition: "Having knowledge or awareness of something.", pronunciation: "NOH-ing", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "landing", definition: "Coming down to the ground after flying; a floor in a staircase.", pronunciation: "LAN-ding", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "largely", definition: "To a great extent; mainly.", pronunciation: "LARJ-lee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "lasting", definition: "Continuing for a long time.", pronunciation: "LAS-ting", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "lantern", definition: "A portable light in a transparent case.", pronunciation: "LAN-tern", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "leaflet", definition: "A small printed paper giving information.", pronunciation: "LEEF-let", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "library", definition: "A building where books are kept and can be borrowed.", pronunciation: "LY-bruh-ree", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "lighter", definition: "Less heavy; brighter; a device for making fire.", pronunciation: "LY-ter", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "limited", definition: "Restricted in extent or amount.", pronunciation: "LIM-i-ted", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "linking", definition: "Connecting things together.", pronunciation: "LINK-ing", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "lobster", definition: "A large shellfish with claws eaten as a delicacy.", pronunciation: "LOB-ster", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "logical", definition: "Based on clear and sensible reasoning.", pronunciation: "LOJ-i-kul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "manager", definition: "A person who is in charge of a business or team.", pronunciation: "MAN-uh-jer", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "mansion", definition: "A very large impressive house.", pronunciation: "MAN-shun", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "measure", definition: "To find the size or amount of something.", pronunciation: "MEZ-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "meeting", definition: "An occasion when people come together to discuss something.", pronunciation: "MEET-ing", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "mention", definition: "To refer to something briefly.", pronunciation: "MEN-shun", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "mineral", definition: "A naturally occurring substance found in the ground.", pronunciation: "MIN-er-ul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "missing", definition: "Not present when expected; lost.", pronunciation: "MIS-ing", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "monster", definition: "A large frightening imaginary creature.", pronunciation: "MON-ster", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "morning", definition: "The part of the day from midnight until noon.", pronunciation: "MOR-ning", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "mystery", definition: "Something that is not explained or understood.", pronunciation: "MIS-tuh-ree", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "natural", definition: "Existing in nature; not made by people.", pronunciation: "NACH-er-ul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "network", definition: "A system of connected things or people.", pronunciation: "NET-wurk", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "nothing", definition: "Not anything; not a single thing.", pronunciation: "NUTH-ing", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "nowhere", definition: "Not in or to any place.", pronunciation: "NOH-wair", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "obvious", definition: "Easily noticed or understood; clear.", pronunciation: "OB-vee-us", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "opening", definition: "A gap or hole; the beginning of something.", pronunciation: "OH-pen-ing", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "operate", definition: "To control and run a machine or system.", pronunciation: "OP-er-ayt", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "opinion", definition: "A view or judgement formed about something.", pronunciation: "uh-PIN-yun", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "outdoor", definition: "Situated in or relating to the open air.", pronunciation: "OWT-dor", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "outside", definition: "The outer side of something; in the open air.", pronunciation: "OWT-syd", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "painted", definition: "Covered with paint; described vividly in words.", pronunciation: "PAYN-ted", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "pattern", definition: "A repeated design or sequence.", pronunciation: "PAT-ern", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "perfect", definition: "Having no faults; complete and correct.", pronunciation: "PUR-fekt", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "perform", definition: "To carry out an action; to entertain an audience.", pronunciation: "per-FORM", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "perhaps", definition: "It is possible that; maybe.", pronunciation: "per-HAPS", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "plastic", definition: "A lightweight synthetic material moulded into many shapes.", pronunciation: "PLAS-tik", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "playing", definition: "Taking part in a game or sport.", pronunciation: "PLAY-ing", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "popular", definition: "Liked by many people.", pronunciation: "POP-yoo-ler", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "problem", definition: "Something difficult that needs to be solved.", pronunciation: "PROB-lem", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "program", definition: "A plan of activities; a set of computer instructions.", pronunciation: "PROH-gram", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "protect", definition: "To keep someone or something safe from harm.", pronunciation: "pruh-TEKT", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "provide", definition: "To make something available for use.", pronunciation: "pruh-VYD", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "publish", definition: "To prepare and issue a book, magazine or article.", pronunciation: "PUB-lish", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "purpose", definition: "The reason for which something is done.", pronunciation: "PUR-pus", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "rainbow", definition: "An arc of colours formed in the sky when sun shines through rain.", pronunciation: "RAYN-boh", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "railway", definition: "A track of rails on which trains travel.", pronunciation: "RAYL-way", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "realise", definition: "To become aware of something (Australian spelling).", pronunciation: "REEL-yz", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "rebuild", definition: "To build something again after it has been damaged.", pronunciation: "ree-BILD", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "recover", definition: "To return to a normal condition after an illness or problem.", pronunciation: "ri-KUV-er", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "regular", definition: "Happening often and at equal intervals; following a pattern.", pronunciation: "REG-yoo-ler", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "relieve", definition: "To reduce or remove pain or worry.", pronunciation: "ri-LEEV", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "request", definition: "To politely ask for something.", pronunciation: "ri-KWEST", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "resolve", definition: "To solve a problem; to decide firmly on something.", pronunciation: "ri-ZOLV", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "respect", definition: "A feeling of admiration; to treat something carefully.", pronunciation: "ri-SPEKT", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "reverse", definition: "To go backwards; the opposite of something.", pronunciation: "ri-VURS", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "rushing", definition: "Moving quickly with urgency.", pronunciation: "RUSH-ing", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "scatter", definition: "To throw in many directions; to go in different directions.", pronunciation: "SKAT-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "science", definition: "The study of the physical and natural world using observation.", pronunciation: "SY-ents", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "screech", definition: "To make a loud high-pitched sound.", pronunciation: "skreech", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "section", definition: "A part of something; a division.", pronunciation: "SEK-shun", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "serious", definition: "Important or significant; solemn and thoughtful.", pronunciation: "SEER-ee-us", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "session", definition: "A period of time spent doing a particular activity.", pronunciation: "SESH-un", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "shelter", definition: "A place giving protection from bad weather or danger.", pronunciation: "SHEL-ter", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "silence", definition: "Complete absence of sound.", pronunciation: "SY-lents", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "similar", definition: "Resembling without being identical.", pronunciation: "SIM-i-ler", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "soldier", definition: "A person who serves in an army.", pronunciation: "SOHL-jer", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "someone", definition: "An unknown or unspecified person.", pronunciation: "SUM-wun", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "somehow", definition: "In a way that is not known or specified.", pronunciation: "SUM-how", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "special", definition: "Better than or different from what is usual.", pronunciation: "SPESH-ul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "station", definition: "A place where trains or buses stop; a building for police.", pronunciation: "STAY-shun", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "stomach", definition: "The organ where food is digested; the abdomen.", pronunciation: "STUM-uk", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "student", definition: "A person who studies at school or university.", pronunciation: "STYOO-dent", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "success", definition: "The achievement of a goal or purpose.", pronunciation: "suk-SES", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "summary", definition: "A brief statement of the main points.", pronunciation: "SUM-uh-ree", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "support", definition: "To give help or encouragement; to hold up.", pronunciation: "suh-PORT", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "surface", definition: "The top or outside layer of something.", pronunciation: "SUR-fis", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "survive", definition: "To continue to live despite danger or difficulty.", pronunciation: "ser-VYV", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "sustain", definition: "To strengthen or support; to keep going.", pronunciation: "suh-STAYN", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "tadpole", definition: "The larva of a frog, toad or newt, living in water.", pronunciation: "TAD-pohl", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "teacher", definition: "A person who teaches, especially in a school.", pronunciation: "TEECH-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "tension", definition: "The feeling of anxiety and nervousness; a strained state.", pronunciation: "TEN-shun", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "tonight", definition: "On the present evening or night.", pronunciation: "tuh-NYT", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "towards", definition: "In the direction of something.", pronunciation: "tuh-WORDZ", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "traffic", definition: "Vehicles moving on roads; the movement of people.", pronunciation: "TRAF-ik", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "trouble", definition: "Difficulty or problems; to make an effort.", pronunciation: "TRUB-ul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "unusual", definition: "Different from what is normal or expected.", pronunciation: "un-YOOZ-yoo-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "usually", definition: "Under normal circumstances; most of the time.", pronunciation: "YOOZH-oo-uh-lee", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "various", definition: "More than one and of different types.", pronunciation: "VAIR-ee-us", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "village", definition: "A small settlement in the countryside.", pronunciation: "VIL-ij", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "volcano", definition: "A mountain with a crater through which lava erupts.", pronunciation: "vol-KAY-noh", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "waiting", definition: "Staying somewhere until something happens.", pronunciation: "WAYT-ing", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "walking", definition: "Moving at a normal speed on foot.", pronunciation: "WAWK-ing", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "warning", definition: "A statement telling of danger or a problem.", pronunciation: "WOR-ning", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "warrior", definition: "A brave or experienced soldier or fighter.", pronunciation: "WOR-ee-er", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "welcome", definition: "To greet someone with pleasure; gladly received.", pronunciation: "WEL-kum", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "welfare", definition: "The health, happiness and fortunes of a person or group.", pronunciation: "WEL-fair", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "western", definition: "Situated in or relating to the west.", pronunciation: "WES-tern", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "whistle", definition: "A device that makes a high sound when you blow it.", pronunciation: "WIS-ul", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "wombats", definition: "Plural of wombat — a stocky Australian burrowing marsupial.", pronunciation: "WOM-bats", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "working", definition: "Doing a job; functioning correctly.", pronunciation: "WUR-king", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "younger", definition: "Of lesser age than another person.", pronunciation: "YUNG-er", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "balloon", definition: "A rubber bag filled with air or gas, often used as a toy.", pronunciation: "buh-LOON", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "bedroom", definition: "A room used for sleeping.", pronunciation: "BED-room", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "biology", definition: "The scientific study of living things.", pronunciation: "by-OL-uh-jee", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "bravery", definition: "Courageous behaviour; willingness to face danger.", pronunciation: "BRAYV-uh-ree", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "brought", definition: "Past tense of bring; carried something to a place.", pronunciation: "brawt", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "builder", definition: "A person who constructs houses and other buildings.", pronunciation: "BIL-der", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "chamber", definition: "A large room; an enclosed space or cavity.", pronunciation: "CHAYM-ber", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "charity", definition: "An organisation that helps people in need; generosity to others.", pronunciation: "CHAIR-i-tee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "climate", definition: "The typical weather conditions of a region over a long time.", pronunciation: "KLY-mit", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "colours", definition: "Plural of colour; the different shades produced by light.", pronunciation: "KUL-erz", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "compass", definition: "An instrument with a magnetic needle for finding direction.", pronunciation: "KUM-pus", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "compete", definition: "To take part in a contest or rivalry against others.", pronunciation: "kum-PEET", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "concept", definition: "An abstract idea or general principle.", pronunciation: "KON-sept", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "content", definition: "Satisfied with what you have; the material contained in something.", pronunciation: "KON-tent", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "costume", definition: "Clothes worn by an actor or at a fancy-dress event.", pronunciation: "KOS-tyoom", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "culture", definition: "The customs, beliefs and arts of a group of people.", pronunciation: "KUL-cher", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "current", definition: "Happening now; a flow of water, air or electricity.", pronunciation: "KUR-ent", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "decided", definition: "Made a firm choice or conclusion.", pronunciation: "di-SY-ded", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "diamond", definition: "A very hard precious gemstone; a four-sided shape.", pronunciation: "DY-mund", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "dingoes", definition: "Plural of dingo; wild Australian dogs with sandy-coloured fur.", pronunciation: "DING-ohz", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "drawing", definition: "Making pictures with a pencil or pen; a picture so made.", pronunciation: "DRAW-ing", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "endless", definition: "Having no end; seeming to go on forever.", pronunciation: "END-les", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "exactly", definition: "Without any difference; precisely correct.", pronunciation: "eg-ZAKT-lee", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "example", definition: "A thing that represents or shows what others of its kind are like.", pronunciation: "eg-ZAM-pul", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "extreme", definition: "Very great or severe; at the farthest possible point.", pronunciation: "ek-STREEM", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "failure", definition: "Lack of success; someone or something that fails.", pronunciation: "FAYL-yer", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "festive", definition: "Relating to a celebration or festival; cheerful.", pronunciation: "FES-tiv", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "fishing", definition: "The activity of catching fish as a sport or for food.", pronunciation: "FISH-ing", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "flutter", definition: "To move wings quickly; to move with quick irregular motion.", pronunciation: "FLUT-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "foreign", definition: "From or relating to another country.", pronunciation: "FOR-en", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "fortune", definition: "A large amount of money; chance or luck.", pronunciation: "FOR-chun", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "fragile", definition: "Easily broken or damaged; delicate.", pronunciation: "FRAJ-ul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "genuine", definition: "Truly what it is said to be; authentic and honest.", pronunciation: "JEN-yoo-in", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "grocery", definition: "A shop selling food and household items; food supplies.", pronunciation: "GROH-ser-ee", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "halfway", definition: "At the middle point between two places or stages.", pronunciation: "HAF-way", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "helpful", definition: "Giving assistance to others; making things easier.", pronunciation: "HELP-ful", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "inspire", definition: "To fill someone with enthusiasm or the urge to do something.", pronunciation: "in-SPYR", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "intense", definition: "Very strong or extreme in degree.", pronunciation: "in-TENS", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "invited", definition: "Asked to come somewhere or take part in something.", pronunciation: "in-VY-ted", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "justice", definition: "Fairness and rightness; the legal system that enforces the law.", pronunciation: "JUS-tis", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "largest", definition: "The biggest in size or amount.", pronunciation: "LAR-jest", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "leather", definition: "A tough material made from animal skin, used for shoes and bags.", pronunciation: "LETH-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "machine", definition: "A device that uses power to do work automatically.", pronunciation: "muh-SHEEN", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "maximum", definition: "The greatest possible or allowed amount.", pronunciation: "MAK-si-mum", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "meaning", definition: "What something means or signifies; the purpose of something.", pronunciation: "MEEN-ing", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "medical", definition: "Relating to medicine or the treatment of illness.", pronunciation: "MED-i-kul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "message", definition: "A spoken or written communication sent from one person to another.", pronunciation: "MES-ij", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "million", definition: "The number one thousand thousand (1,000,000).", pronunciation: "MIL-yun", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "minimum", definition: "The smallest possible or allowed amount.", pronunciation: "MIN-i-mum", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "mixture", definition: "A combination of different things mixed together.", pronunciation: "MIK-cher", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "musical", definition: "Relating to music; having a natural talent for music.", pronunciation: "MYOOZ-i-kul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "organic", definition: "Relating to living things; food grown without chemicals.", pronunciation: "or-GAN-ik", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "outback", definition: "The remote inland areas of Australia, far from cities.", pronunciation: "OWT-bak", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "package", definition: "A wrapped or boxed parcel; a set of related things offered together.", pronunciation: "PAK-ij", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "painful", definition: "Causing pain; distressing or upsetting.", pronunciation: "PAYN-ful", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "partner", definition: "A person who shares an activity or responsibility with another.", pronunciation: "PART-ner", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "patient", definition: "Able to wait calmly without getting upset; a person receiving medical care.", pronunciation: "PAY-shunt", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "penguin", definition: "A black-and-white seabird from the southern hemisphere that cannot fly.", pronunciation: "PENG-gwin", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "picture", definition: "A painting, drawing or photograph; a mental image.", pronunciation: "PIK-cher", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "pottery", definition: "Objects made from clay that is shaped and baked.", pronunciation: "POT-er-ee", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "predict", definition: "To say what you think will happen in the future.", pronunciation: "pri-DIKT", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "present", definition: "The time that exists now; a gift; to show or introduce something.", pronunciation: "PREZ-ent", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "prevent", definition: "To stop something from happening.", pronunciation: "pri-VENT", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "process", definition: "A series of actions or steps taken to achieve a result.", pronunciation: "PROH-ses", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "produce", definition: "To make or create something; fresh food grown on farms.", pronunciation: "pruh-DYOOS", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "promise", definition: "To say you will definitely do something; a declaration of intent.", pronunciation: "PROM-is", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "quarter", definition: "One of four equal parts of something; fifteen minutes.", pronunciation: "KWOR-ter", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "quickly", definition: "Moving or done at a fast speed; in a short amount of time.", pronunciation: "KWIK-lee", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "reading", definition: "Looking at and understanding written words.", pronunciation: "REED-ing", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "reality", definition: "The state of things as they actually are, not imagined.", pronunciation: "ree-AL-i-tee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "receive", definition: "To be given something by someone.", pronunciation: "ri-SEEV", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "related", definition: "Connected to or associated with something.", pronunciation: "ri-LAY-ted", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "replace", definition: "To put something new in place of another; to take the place of.", pronunciation: "ri-PLAYS", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "require", definition: "To need something; to make something necessary.", pronunciation: "ri-KWYR", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "respond", definition: "To say or do something in reply.", pronunciation: "ri-SPOND", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "results", definition: "The outcomes or effects of an action or event.", pronunciation: "ri-ZULTZ", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "revenge", definition: "Doing something harmful to someone who has harmed you.", pronunciation: "ri-VENJ", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "rolling", definition: "Moving by turning over and over; continuous.", pronunciation: "ROHL-ing", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "running", definition: "Moving quickly on foot; managing or operating something.", pronunciation: "RUN-ing", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "sadness", definition: "The state of feeling unhappy or sorrowful.", pronunciation: "SAD-nes", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "sailing", definition: "Travelling on water using the wind to power sails.", pronunciation: "SAYL-ing", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "service", definition: "Work done for others; a system that provides something to the public.", pronunciation: "SUR-vis", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "sharing", definition: "Using or having something with others; telling others about something.", pronunciation: "SHAIR-ing", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "singing", definition: "Making musical sounds with your voice.", pronunciation: "SING-ing", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "sixteen", definition: "The number 16.", pronunciation: "sik-STEEN", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "society", definition: "People living together with shared laws and customs.", pronunciation: "suh-SY-uh-tee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "species", definition: "A group of animals or plants of the same type that can breed together.", pronunciation: "SPEE-sheez", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "stadium", definition: "A large sports ground with rows of seats for spectators.", pronunciation: "STAY-dee-um", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "stamina", definition: "The ability to keep doing something tiring for a long time.", pronunciation: "STAM-i-nuh", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "strange", definition: "Unusual or surprising; not previously encountered.", pronunciation: "stranj", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "stretch", definition: "To pull something to make it longer or wider; to reach out.", pronunciation: "strech", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "subject", definition: "A topic of study or discussion; to cause someone to experience something.", pronunciation: "SUB-jekt", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "suppose", definition: "To assume something is probably true; to expect.", pronunciation: "suh-POHZ", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "talking", definition: "Speaking words aloud; having a conversation.", pronunciation: "TAW-king", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "telling", definition: "Communicating information to someone by speaking or writing.", pronunciation: "TEL-ing", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "testing", definition: "Checking whether something works or is correct.", pronunciation: "TEST-ing", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "thirsty", definition: "Feeling a need to drink; eager to have or know something.", pronunciation: "THUR-stee", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "thought", definition: "An idea formed in the mind; the past tense of think.", pronunciation: "thawt", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "through", definition: "Moving in one side and out the other; because of.", pronunciation: "throo", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "thunder", definition: "The loud rumbling sound heard after lightning during a storm.", pronunciation: "THUN-der", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "totally", definition: "Completely; in every way.", pronunciation: "TOH-tuh-lee", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "typical", definition: "Having the qualities of a particular type; normal.", pronunciation: "TIP-i-kul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "unknown", definition: "Not known or familiar; a person or thing not identified.", pronunciation: "un-NOHN", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "upwards", definition: "Moving towards a higher position or level.", pronunciation: "UP-werdz", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "vaccine", definition: "A substance injected into the body to protect against a disease.", pronunciation: "VAK-seen", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "weather", definition: "The conditions of the atmosphere at a particular place and time.", pronunciation: "WETH-er", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "website", definition: "A set of pages on the internet about a particular topic.", pronunciation: "WEB-syt", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "wedding", definition: "A ceremony where two people get married.", pronunciation: "WED-ing", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "weekend", definition: "Saturday and Sunday; the end of the working week.", pronunciation: "WEEK-end", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "whether", definition: "Expressing a doubt or choice between two alternatives.", pronunciation: "WETH-er", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "willing", definition: "Ready and happy to do something without being forced.", pronunciation: "WIL-ing", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "without", definition: "Not having something; in the absence of.", pronunciation: "with-OWT", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "wonders", definition: "Amazing or remarkable things; to feel curious about something.", pronunciation: "WUN-derz", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "worried", definition: "Feeling anxious and troubled about something.", pronunciation: "WUR-eed", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "writing", definition: "The activity of creating text; written material or handwriting.", pronunciation: "RY-ting", hasRepeatingLetters: true, hasRareLetters: true },
];
