// words-6.js — 6-letter Australian English word list for Aussie Word Challenge

export const WORDS_6 = [
  { word: "absorb", definition: "To soak up or take in a substance.", pronunciation: "ab-ZORB", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "accept", definition: "To take or receive something offered.", pronunciation: "ak-SEPT", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "access", definition: "The ability or right to use or enter something.", pronunciation: "AK-ses", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "active", definition: "Moving or working; taking part in activities.", pronunciation: "AK-tiv", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "actual", definition: "Real and existing, not imaginary.", pronunciation: "AK-choo-ul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "advice", definition: "Suggestions about what someone should do in a situation.", pronunciation: "ad-VYS", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "afford", definition: "To have enough money to pay for something.", pronunciation: "uh-FORD", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "afraid", definition: "Feeling fear or anxiety about something.", pronunciation: "uh-FRAYD", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "agency", definition: "A business that provides a particular service.", pronunciation: "AY-jen-see", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "almost", definition: "Very nearly but not quite.", pronunciation: "AWL-mohst", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "always", definition: "At all times; every time.", pronunciation: "AWL-wayz", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "amount", definition: "The total quantity or sum of something.", pronunciation: "uh-MOWNT", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "anchor", definition: "A heavy object dropped from a ship to stop it drifting.", pronunciation: "ANG-ker", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "animal", definition: "A living creature that is not a plant or human.", pronunciation: "AN-i-mul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "annual", definition: "Happening once a year; a plant that lives for one year.", pronunciation: "AN-yoo-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "anyone", definition: "Any person at all.", pronunciation: "EN-ee-wun", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "anyway", definition: "Despite what has just been said; in any case.", pronunciation: "EN-ee-way", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "appear", definition: "To come into sight; to seem to be.", pronunciation: "uh-PEER", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "around", definition: "On every side; in various places.", pronunciation: "uh-ROWND", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "attack", definition: "To take aggressive action against someone or something.", pronunciation: "uh-TAK", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "attend", definition: "To be present at a place or event.", pronunciation: "uh-TEND", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "autumn", definition: "The season after summer when leaves fall from trees.", pronunciation: "AW-tum", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "banded", definition: "Marked with stripes or bands of colour.", pronunciation: "BAN-ded", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "basket", definition: "A container made of woven material.", pronunciation: "BAS-ket", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "battle", definition: "A fight between two armies or groups.", pronunciation: "BAT-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "become", definition: "To change and start to be something different.", pronunciation: "bi-KUM", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "before", definition: "Earlier than; in front of.", pronunciation: "bi-FOR", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "behind", definition: "At or towards the back of something.", pronunciation: "bi-HYND", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "belong", definition: "To be the property of someone; to feel part of a group.", pronunciation: "bi-LONG", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "better", definition: "Of a higher quality or more suitable than another.", pronunciation: "BET-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "bother", definition: "To worry or disturb someone; to take the trouble to do something.", pronunciation: "BOTH-er", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "bottle", definition: "A container with a narrow neck for holding liquids.", pronunciation: "BOT-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "bright", definition: "Giving out or filled with light; intelligent.", pronunciation: "bryt", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "broken", definition: "Smashed into pieces; not working.", pronunciation: "BROH-ken", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "bubble", definition: "A thin sphere of liquid filled with air.", pronunciation: "BUB-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "bucket", definition: "A round open container with a handle for carrying water.", pronunciation: "BUK-it", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "budget", definition: "A plan of how money will be earned and spent.", pronunciation: "BUJ-it", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "bundle", definition: "A collection of things tied together.", pronunciation: "BUN-dul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "burrow", definition: "A hole or tunnel dug by a rabbit or other animal to live in.", pronunciation: "BUR-oh", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "button", definition: "A small fastener sewn on clothing; a small disc you press.", pronunciation: "BUT-un", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "cactus", definition: "A plant that grows in dry areas and is covered in spines.", pronunciation: "KAK-tus", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "camera", definition: "A device used for taking photographs or making films.", pronunciation: "KAM-er-uh", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "candle", definition: "A stick of wax with a wick that burns to give light.", pronunciation: "KAN-dul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "canyon", definition: "A deep gorge with steep sides, often with a river at the bottom.", pronunciation: "KAN-yun", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "castle", definition: "A large medieval stone building with towers, built for defence.", pronunciation: "KAS-ul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "casual", definition: "Relaxed and informal; not regular or permanent.", pronunciation: "KAZ-yoo-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "cellar", definition: "A room below ground level in a building, used for storage.", pronunciation: "SEL-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "cement", definition: "A grey powder mixed with water used in building.", pronunciation: "si-MENT", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "centre", definition: "The middle point of something (Australian spelling).", pronunciation: "SEN-ter", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "chance", definition: "A possibility that something will happen.", pronunciation: "chans", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "change", definition: "To become different; to replace one thing with another.", pronunciation: "chaynj", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "charge", definition: "To ask a price; to accuse someone; to rush forward.", pronunciation: "charj", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "choice", definition: "The act of choosing between two or more options.", pronunciation: "choys", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "cobalt", definition: "A hard blue-white metallic element used in making alloys.", pronunciation: "KOH-bawlt", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "cobble", definition: "A small round stone used to pave roads.", pronunciation: "KOB-ul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "commit", definition: "To do something, especially something wrong; to dedicate.", pronunciation: "kuh-MIT", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "common", definition: "Found or happening often; shared by all.", pronunciation: "KOM-un", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "corner", definition: "The point where two edges or walls meet.", pronunciation: "KOR-ner", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "cotton", definition: "A soft white plant fibre used to make fabric.", pronunciation: "KOT-un", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "cousin", definition: "The child of your aunt or uncle.", pronunciation: "KUZ-un", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "custom", definition: "A tradition practised in a community; made specially for someone.", pronunciation: "KUS-tum", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "danger", definition: "The possibility of suffering harm or injury.", pronunciation: "DAYN-jer", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "dangle", definition: "To hang or swing loosely.", pronunciation: "DANG-ul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "define", definition: "To state exactly what something means.", pronunciation: "di-FYN", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "demand", definition: "To ask for something firmly; the desire for goods or services.", pronunciation: "di-MAND", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "desert", definition: "A large dry area of land with very little rain.", pronunciation: "DEZ-ert", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "detail", definition: "A small individual part of something.", pronunciation: "DEE-tayl", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "differ", definition: "To be unlike something else; to disagree.", pronunciation: "DIF-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "dinner", definition: "The main meal of the day, usually eaten in the evening.", pronunciation: "DIN-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "direct", definition: "Going from one place to another without turning; to guide.", pronunciation: "duh-REKT", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "divide", definition: "To separate into parts; to share equally.", pronunciation: "di-VYD", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "donkey", definition: "An animal like a small horse with long ears.", pronunciation: "DONG-kee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "double", definition: "Twice as much; consisting of two equal parts.", pronunciation: "DUB-ul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "dragon", definition: "A mythical fire-breathing creature with wings.", pronunciation: "DRAG-un", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "drawer", definition: "A box-like container that slides in and out of furniture.", pronunciation: "draw-er", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "during", definition: "Throughout the whole of a period of time.", pronunciation: "DYOOR-ing", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "either", definition: "One or the other of two things.", pronunciation: "EE-ther", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "endure", definition: "To suffer something painful; to last a long time.", pronunciation: "en-DYOOR", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "engage", definition: "To take part in something; to attract attention.", pronunciation: "en-GAYJ", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "engine", definition: "A machine that produces power by burning fuel.", pronunciation: "EN-jin", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "enough", definition: "As much as is needed or wanted.", pronunciation: "i-NUF", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "ensure", definition: "To make certain that something will happen.", pronunciation: "en-SHOOR", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "escape", definition: "To get away from a place where you are held.", pronunciation: "i-SKAYP", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "estate", definition: "A large area of land owned by a person; someone's property.", pronunciation: "i-STAYT", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "evolve", definition: "To develop gradually over time.", pronunciation: "i-VOLV", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "exceed", definition: "To go beyond a limit.", pronunciation: "ek-SEED", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "excuse", definition: "A reason given to explain or justify behaviour.", pronunciation: "ek-SKYOOS", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "expand", definition: "To become or make larger.", pronunciation: "ek-SPAND", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "expert", definition: "A person with great knowledge or skill in a particular area.", pronunciation: "EK-spurt", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "export", definition: "To send goods to another country for sale.", pronunciation: "EK-sport", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "extend", definition: "To make something longer or larger.", pronunciation: "ek-STEND", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "fabric", definition: "Cloth or material made from fibres.", pronunciation: "FAB-rik", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "factor", definition: "Something that contributes to a result.", pronunciation: "FAK-ter", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "fallen", definition: "Past participle of fall; having dropped to a lower position.", pronunciation: "FAW-len", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "family", definition: "A group of people related by blood or marriage.", pronunciation: "FAM-i-lee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "famous", definition: "Known and recognised by many people.", pronunciation: "FAY-mus", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "fallow", definition: "Farmland left without crops for a season to regain fertility.", pronunciation: "FAL-oh", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "finger", definition: "One of the long thin parts of your hand.", pronunciation: "FING-er", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "fiscal", definition: "Relating to government finances and taxes.", pronunciation: "FIS-kul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "follow", definition: "To go after someone or something; to obey a rule.", pronunciation: "FOL-oh", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "forest", definition: "A large area covered with trees.", pronunciation: "FOR-est", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "formal", definition: "Following rules and conventions; official.", pronunciation: "FOR-mul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "fossil", definition: "The preserved remains of an ancient animal or plant in rock.", pronunciation: "FOS-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "fourth", definition: "Coming after the third in order.", pronunciation: "forth", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "freeze", definition: "To become extremely cold; to turn into ice.", pronunciation: "freez", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "friend", definition: "A person you know well and enjoy spending time with.", pronunciation: "frend", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "frozen", definition: "Turned into ice; preserved at very low temperature.", pronunciation: "FROH-zen", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "future", definition: "The time that will come after the present.", pronunciation: "FYOO-cher", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "garden", definition: "A piece of ground next to a house where plants are grown.", pronunciation: "GAR-den", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "gather", definition: "To come together in a group; to collect things.", pronunciation: "GATH-er", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "gentle", definition: "Mild and kind; not rough or violent.", pronunciation: "JEN-tul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "giving", definition: "Handing something to another person; generous.", pronunciation: "GIV-ing", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "global", definition: "Relating to the whole world.", pronunciation: "GLOH-bul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "golden", definition: "Made of gold; having a bright yellow colour.", pronunciation: "GOHL-den", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "govern", definition: "To be in charge of running a country or area.", pronunciation: "GUV-ern", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "ground", definition: "The solid surface of the earth; a reason or basis.", pronunciation: "grownd", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "guitar", definition: "A stringed musical instrument played by plucking or strumming.", pronunciation: "gi-TAR", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "happen", definition: "To take place, often by chance.", pronunciation: "HAP-en", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "harrow", definition: "A farm tool for breaking up soil; to distress greatly.", pronunciation: "HA-roh", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "height", definition: "The measurement from the bottom to the top of something.", pronunciation: "hyt", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "hidden", definition: "Put out of sight; not known to others.", pronunciation: "HID-en", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "higher", definition: "At a greater height or level.", pronunciation: "HY-er", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "hollow", definition: "Having an empty space inside; not solid.", pronunciation: "HOL-oh", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "honest", definition: "Telling the truth and not cheating or stealing.", pronunciation: "ON-est", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "hungry", definition: "Feeling the need or desire to eat.", pronunciation: "HUNG-gree", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "hustle", definition: "To push and shove; to work energetically.", pronunciation: "HUS-ul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "impact", definition: "The effect or influence of one thing on another.", pronunciation: "IM-pakt", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "import", definition: "To bring goods in from another country.", pronunciation: "IM-port", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "insect", definition: "A small creature with six legs and usually wings.", pronunciation: "IN-sekt", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "insist", definition: "To say something very firmly that you want or believe.", pronunciation: "in-SIST", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "inside", definition: "In the inner part of something; indoors.", pronunciation: "IN-syd", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "intend", definition: "To plan to do something.", pronunciation: "in-TEND", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "invest", definition: "To put money into something to make a profit.", pronunciation: "in-VEST", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "island", definition: "A piece of land completely surrounded by water.", pronunciation: "EYE-lund", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "itself", definition: "Used to refer to something previously mentioned.", pronunciation: "it-SELF", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "jacket", definition: "A short coat.", pronunciation: "JAK-it", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "jigsaw", definition: "A puzzle made of cut-up pieces of a picture that fit together.", pronunciation: "JIG-saw", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "jungle", definition: "Dense tropical vegetation; a confusing difficult situation.", pronunciation: "JUNG-ul", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "junior", definition: "Younger or of lower rank; relating to younger students.", pronunciation: "JOO-nee-er", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "kernel", definition: "The softer part inside a nut or seed.", pronunciation: "KUR-nul", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "kettle", definition: "A container with a lid and spout used to boil water.", pronunciation: "KET-ul", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "kitten", definition: "A young cat.", pronunciation: "KIT-en", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "knight", definition: "A man granted an honorary title by a king or queen.", pronunciation: "nyt", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "lagoon", definition: "A shallow body of water separated from the sea by a reef or sandbank.", pronunciation: "luh-GOON", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "lately", definition: "Recently; in the recent past.", pronunciation: "LAYT-lee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "latest", definition: "Most recent; the newest.", pronunciation: "LAY-test", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "launch", definition: "To send a rocket into space; to start a new product or project.", pronunciation: "lawnch", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "lawyer", definition: "A person who practises law and gives legal advice.", pronunciation: "LAW-yer", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "league", definition: "A group of sports teams that compete against each other.", pronunciation: "leeg", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "length", definition: "The measurement of something from one end to the other.", pronunciation: "length", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "lesser", definition: "Of a smaller size or importance.", pronunciation: "LES-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "letter", definition: "A written message; one of the symbols in an alphabet.", pronunciation: "LET-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "likely", definition: "Probable; having a good chance of happening.", pronunciation: "LYK-lee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "little", definition: "Small in size or amount.", pronunciation: "LIT-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "lizard", definition: "A reptile with four legs and a long tail.", pronunciation: "LIZ-erd", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "longer", definition: "Of greater length; for a greater period of time.", pronunciation: "LONG-er", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "lovely", definition: "Very attractive or pleasant.", pronunciation: "LUV-lee", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "lowest", definition: "At the smallest height or level.", pronunciation: "LOH-est", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "margin", definition: "The edge or border of something; the difference between two amounts.", pronunciation: "MAR-jin", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "market", definition: "A place where goods are bought and sold.", pronunciation: "MAR-ket", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "master", definition: "A person who is very skilled at something; to learn thoroughly.", pronunciation: "MAS-ter", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "mature", definition: "Fully developed; behaving sensibly like an adult.", pronunciation: "muh-TYOOR", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "meadow", definition: "A field covered in grass and wildflowers.", pronunciation: "MED-oh", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "mental", definition: "Relating to the mind.", pronunciation: "MEN-tul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "method", definition: "A particular way of doing something.", pronunciation: "METH-ud", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "middle", definition: "The part or position that is equally distant from all sides.", pronunciation: "MID-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "mirror", definition: "A flat surface of glass that reflects images.", pronunciation: "MIR-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "modern", definition: "Relating to the present time; not old-fashioned.", pronunciation: "MOD-ern", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "moment", definition: "A very short period of time.", pronunciation: "MOH-ment", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "monkey", definition: "A primate animal with a long tail.", pronunciation: "MUNG-kee", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "mortar", definition: "A mixture of cement used in building; a bowl for grinding.", pronunciation: "MOR-ter", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "mother", definition: "A female parent.", pronunciation: "MUTH-er", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "muster", definition: "To gather soldiers or animals together; to summon an effort.", pronunciation: "MUS-ter", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "myself", definition: "Used by a speaker to refer to themselves.", pronunciation: "my-SELF", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "namely", definition: "That is to say; in other words.", pronunciation: "NAYM-lee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "narrow", definition: "Small in width; limited in range.", pronunciation: "NAR-oh", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "nation", definition: "A large group of people united by common history and language.", pronunciation: "NAY-shun", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "nature", definition: "The natural world of plants and animals; the character of something.", pronunciation: "NAY-cher", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "nearly", definition: "Almost but not quite.", pronunciation: "NEER-lee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "needle", definition: "A thin pointed instrument used for sewing.", pronunciation: "NEE-dul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "nickel", definition: "A silver-white metallic element; a five-cent coin.", pronunciation: "NIK-ul", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "normal", definition: "Conforming to a usual standard; typical.", pronunciation: "NOR-mul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "notice", definition: "To become aware of something; a written announcement.", pronunciation: "NOH-tis", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "object", definition: "A thing you can see or touch; to disagree with something.", pronunciation: "OB-jekt", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "obtain", definition: "To get something, especially with effort.", pronunciation: "ob-TAYN", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "office", definition: "A room or building used for working in.", pronunciation: "OF-is", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "orange", definition: "A round citrus fruit; a colour between red and yellow.", pronunciation: "OR-anj", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "origin", definition: "The point where something begins or is created.", pronunciation: "OR-i-jin", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "outfit", definition: "A set of clothes worn together.", pronunciation: "OWT-fit", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "outlaw", definition: "A person who has broken the law; to make something illegal.", pronunciation: "OWT-law", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "output", definition: "The amount of something produced.", pronunciation: "OWT-put", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "oyster", definition: "A shellfish that can produce pearls.", pronunciation: "OY-ster", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "paddle", definition: "A short oar used to propel a canoe; to move through shallow water.", pronunciation: "PAD-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "parrot", definition: "A brightly coloured tropical bird that can mimic speech.", pronunciation: "PA-rut", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "pencil", definition: "A thin writing instrument with a graphite core.", pronunciation: "PEN-sul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "pepper", definition: "A spicy seasoning used in cooking; a type of vegetable.", pronunciation: "PEP-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "period", definition: "A length of time; a full stop at the end of a sentence.", pronunciation: "PEER-ee-ud", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "permit", definition: "To allow something to happen; an official document.", pronunciation: "PUR-mit", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "pickle", definition: "A vegetable preserved in vinegar; a difficult situation.", pronunciation: "PIK-ul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "pillow", definition: "A soft cushion used to rest your head on while sleeping.", pronunciation: "PIL-oh", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "pirate", definition: "A person who robs ships at sea.", pronunciation: "PY-rut", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "plenty", definition: "A large amount; more than enough.", pronunciation: "PLEN-tee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "podium", definition: "A raised platform on which a speaker or conductor stands.", pronunciation: "POH-dee-um", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "police", definition: "The official body of people whose job is to prevent crime.", pronunciation: "puh-LEES", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "portal", definition: "A doorway or gate; a website that acts as an entry point.", pronunciation: "POR-tul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "prefer", definition: "To like one thing better than another.", pronunciation: "pri-FUR", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "pretty", definition: "Attractive and pleasing to look at.", pronunciation: "PRIT-ee", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "prince", definition: "The son of a king and queen; a male ruler.", pronunciation: "prins", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "prison", definition: "A building where criminals are kept as punishment.", pronunciation: "PRIZ-un", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "proper", definition: "Correct and appropriate; genuine.", pronunciation: "PROP-er", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "puddle", definition: "A small pool of water on the ground.", pronunciation: "PUD-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "purple", definition: "A colour between red and blue.", pronunciation: "PUR-pul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "puzzle", definition: "A game or problem that requires thinking to solve.", pronunciation: "PUZ-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "rabbit", definition: "A small furry animal with long ears that lives in burrows.", pronunciation: "RAB-it", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "rattle", definition: "To make a rapid series of short sharp sounds.", pronunciation: "RAT-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "reason", definition: "A cause or explanation for something.", pronunciation: "REE-zun", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "recent", definition: "Having happened not long ago.", pronunciation: "REE-sent", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "record", definition: "To write down or store information; a best achievement.", pronunciation: "REK-erd", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "reduce", definition: "To make smaller in size or amount.", pronunciation: "ri-DYOOS", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "remain", definition: "To stay in the same place or condition.", pronunciation: "ri-MAYN", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "remove", definition: "To take something away from its place.", pronunciation: "ri-MOOV", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "repair", definition: "To fix something that is broken or damaged.", pronunciation: "ri-PAIR", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "repeat", definition: "To say or do something again.", pronunciation: "ri-PEET", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "result", definition: "The outcome or consequence of something.", pronunciation: "ri-ZULT", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "return", definition: "To go back to a place; to give something back.", pronunciation: "ri-TURN", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "reveal", definition: "To make something known or visible.", pronunciation: "ri-VEEL", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "riddle", definition: "A question designed to be puzzling or amusing.", pronunciation: "RID-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "school", definition: "A place where children go to be educated.", pronunciation: "skool", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "screen", definition: "A flat surface for displaying images; a thin partition.", pronunciation: "skreen", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "second", definition: "The position numbered two; a unit of time.", pronunciation: "SEK-und", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "select", definition: "To choose someone or something.", pronunciation: "si-LEKT", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "settle", definition: "To end a dispute; to make your home in a new place.", pronunciation: "SET-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "shadow", definition: "A dark shape made when an object blocks light.", pronunciation: "SHAD-oh", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "shower", definition: "A device spraying water to wash under; a brief rain.", pronunciation: "SHOW-er", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "silver", definition: "A shiny white precious metal; a greyish-white colour.", pronunciation: "SIL-ver", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "simple", definition: "Easy to do or understand; not complicated.", pronunciation: "SIM-pul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "single", definition: "Only one; not married; a record with one main song.", pronunciation: "SING-ul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "sister", definition: "A girl or woman who has the same parents as you.", pronunciation: "SIS-ter", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "sketch", definition: "A quick rough drawing; a short comedy performance.", pronunciation: "skech", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "smooth", definition: "Having an even surface without bumps; happening without problems.", pronunciation: "smooth", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "sneaky", definition: "Doing things in a secret and dishonest way.", pronunciation: "SNEE-kee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "socket", definition: "A hollow into which something fits; an electric power outlet.", pronunciation: "SOK-it", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "sorrow", definition: "A feeling of deep sadness or regret.", pronunciation: "SOR-oh", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "spider", definition: "A small creature with eight legs that spins webs.", pronunciation: "SPY-der", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "spiral", definition: "A shape that winds around a centre point, getting further away.", pronunciation: "SPY-rul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "spirit", definition: "The non-physical part of a person; enthusiasm and liveliness.", pronunciation: "SPIR-it", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "splash", definition: "To scatter liquid in drops; the sound this makes.", pronunciation: "splash", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "spring", definition: "The season after winter; a coiled metal object; to leap.", pronunciation: "spring", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "square", definition: "A shape with four equal sides and right angles.", pronunciation: "skwair", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "stable", definition: "Not likely to change or fall; a building for horses.", pronunciation: "STAY-bul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "starve", definition: "To suffer or die from lack of food.", pronunciation: "starv", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "sticky", definition: "Covered in a substance that things cling to.", pronunciation: "STIK-ee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "stitch", definition: "A single loop of thread in sewing or knitting.", pronunciation: "stich", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "stolen", definition: "Past participle of steal; taken without permission.", pronunciation: "STOH-len", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "strain", definition: "To injure a muscle by stretching it too much; an effort.", pronunciation: "strayn", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "stream", definition: "A small narrow river; to flow continuously.", pronunciation: "streem", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "strict", definition: "Demanding complete obedience to rules.", pronunciation: "strikt", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "strong", definition: "Having great physical power; not easily damaged.", pronunciation: "strong", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "struck", definition: "Past tense of strike; hit with force.", pronunciation: "struk", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "stupid", definition: "Lacking intelligence; foolish.", pronunciation: "STYOO-pid", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "submit", definition: "To give something to someone in authority.", pronunciation: "sub-MIT", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "suburb", definition: "A residential area on the outskirts of a city.", pronunciation: "SUB-urb", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "sudden", definition: "Happening quickly and unexpectedly.", pronunciation: "SUD-en", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "summer", definition: "The warmest season of the year.", pronunciation: "SUM-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "supply", definition: "To provide what is needed; a stock of something available.", pronunciation: "suh-PLY", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "swivel", definition: "A joint that allows rotation in one direction.", pronunciation: "SWIV-ul", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "switch", definition: "A device for turning something on or off; to change.", pronunciation: "swich", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "symbol", definition: "A thing that represents something else.", pronunciation: "SIM-bul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "system", definition: "A set of things working together as a whole.", pronunciation: "SIS-tem", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "target", definition: "An object aimed at in shooting; a goal to achieve.", pronunciation: "TAR-get", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "temple", definition: "A place of worship; the flat area on either side of the forehead.", pronunciation: "TEM-pul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "thanks", definition: "An expression of gratitude.", pronunciation: "thankss", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "theory", definition: "A set of ideas meant to explain something.", pronunciation: "THEER-ee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "though", definition: "Despite the fact that; however.", pronunciation: "thoh", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "thrash", definition: "To hit someone or something repeatedly.", pronunciation: "thrash", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "tickle", definition: "To lightly touch someone causing laughter.", pronunciation: "TIK-ul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "timber", definition: "Wood that has been cut for use in building.", pronunciation: "TIM-ber", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "tinker", definition: "To make small changes to something to improve it.", pronunciation: "TINK-er", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "tissue", definition: "A soft thin piece of paper used as a handkerchief.", pronunciation: "TISH-oo", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "tomato", definition: "A round red fruit eaten as a vegetable.", pronunciation: "tuh-MAH-toh", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "tongue", definition: "The muscular organ in your mouth used for tasting and speaking.", pronunciation: "tung", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "toucan", definition: "A tropical bird with a large brightly coloured beak.", pronunciation: "TOO-kan", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "travel", definition: "To make a journey from one place to another.", pronunciation: "TRAV-ul", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "trowel", definition: "A small tool for spreading mortar or planting.", pronunciation: "TROW-ul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "tunnel", definition: "An underground passage.", pronunciation: "TUN-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "turkey", definition: "A large bird often eaten at Christmas in Australia.", pronunciation: "TUR-kee", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "turtle", definition: "A slow-moving reptile with a shell on its back.", pronunciation: "TUR-tul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "tussle", definition: "A short struggle or fight.", pronunciation: "TUS-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "unfold", definition: "To open out from a folded state; to develop.", pronunciation: "un-FOHLD", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "unique", definition: "Being the only one of its kind.", pronunciation: "yoo-NEEK", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "unlock", definition: "To open a lock with a key.", pronunciation: "un-LOK", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "unsafe", definition: "Dangerous; not protected from risk.", pronunciation: "un-SAYF", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "useful", definition: "Able to be used for a practical purpose.", pronunciation: "YOOS-ful", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "valley", definition: "A low area of land between hills.", pronunciation: "VAL-ee", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "violet", definition: "A purple-blue colour; a small plant with fragrant flowers.", pronunciation: "VY-uh-let", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "volume", definition: "The amount of space inside something; the loudness of sound.", pronunciation: "VOL-yoom", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "voyage", definition: "A long journey, especially by sea.", pronunciation: "VOY-ij", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "walrus", definition: "A large Arctic sea animal with two long tusks.", pronunciation: "WAWL-rus", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "wander", definition: "To walk around without a fixed destination.", pronunciation: "WON-der", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "warmth", definition: "The quality of being warm; friendly and caring behaviour.", pronunciation: "warmth", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "wealth", definition: "A large amount of money or valuable possessions.", pronunciation: "welth", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "weekly", definition: "Happening once a week.", pronunciation: "WEEK-lee", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "window", definition: "An opening in a wall covered with glass.", pronunciation: "WIN-doh", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "winner", definition: "A person or team that wins a competition.", pronunciation: "WIN-er", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "winter", definition: "The coldest season of the year.", pronunciation: "WIN-ter", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "within", definition: "Inside or not beyond a particular boundary.", pronunciation: "with-IN", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "wonder", definition: "To think about something curiously; a feeling of amazement.", pronunciation: "WUN-der", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "wooden", definition: "Made of wood.", pronunciation: "WUD-en", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "worthy", definition: "Deserving respect, attention or praise.", pronunciation: "WUR-thee", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "yellow", definition: "The colour of a lemon or sunshine.", pronunciation: "YEL-oh", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "zipper", definition: "A fastening device with interlocking teeth.", pronunciation: "ZIP-er", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "absent", definition: "Not present in a place; missing.", pronunciation: "AB-sent", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "barbie", definition: "Australian slang for a barbecue grill or barbecue party.", pronunciation: "BAR-bee", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "bonzer", definition: "Australian slang for something excellent or wonderful.", pronunciation: "BON-zer", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "border", definition: "The edge or boundary between two areas or countries.", pronunciation: "BOR-der", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "bounce", definition: "To spring back after hitting a surface.", pronunciation: "bowns", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "brolga", definition: "A large grey Australian crane known for its dancing display.", pronunciation: "BROL-guh", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "bustle", definition: "Excited and busy activity; to move hurriedly.", pronunciation: "BUS-ul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "butter", definition: "A yellow fat made from cream, spread on bread.", pronunciation: "BUT-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "circle", definition: "A perfectly round flat shape.", pronunciation: "SUR-kul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "clever", definition: "Quick to understand and learn; intelligent.", pronunciation: "KLEV-er", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "cobber", definition: "Australian slang for a close friend or mate.", pronunciation: "KOB-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "colour", definition: "The property of an object described as red, blue, green, etc.", pronunciation: "KUL-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "copper", definition: "A reddish-brown metallic element; informal term for a police officer.", pronunciation: "KOP-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "create", definition: "To make or produce something new.", pronunciation: "kree-AYT", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "credit", definition: "Praise given to someone for an achievement; money in an account.", pronunciation: "KRED-it", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "crisis", definition: "A time of intense difficulty or danger.", pronunciation: "KRY-sis", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "damage", definition: "Physical harm that reduces value or usefulness.", pronunciation: "DAM-ij", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "deadly", definition: "Causing or likely to cause death; very serious.", pronunciation: "DED-lee", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "decide", definition: "To make a choice after considering options.", pronunciation: "di-SYD", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "defeat", definition: "To win against someone in a contest; a loss.", pronunciation: "di-FEET", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "defend", definition: "To protect from attack or harm.", pronunciation: "di-FEND", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "design", definition: "A plan or drawing for making something; to plan and create.", pronunciation: "di-ZYN", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "detect", definition: "To discover or notice something not obvious.", pronunciation: "di-TEKT", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "dollar", definition: "The unit of currency used in Australia.", pronunciation: "DOL-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "drongo", definition: "Australian slang for a silly or stupid person; also a type of bird.", pronunciation: "DRONG-oh", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "driven", definition: "Motivated and determined; past participle of drive.", pronunciation: "DRIV-en", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "effect", definition: "A change that is a result of an action or cause.", pronunciation: "i-FEKT", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "effort", definition: "Physical or mental energy used to do something.", pronunciation: "EF-ert", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "empire", definition: "A group of nations ruled by a single authority.", pronunciation: "EM-pyr", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "entire", definition: "Complete; with nothing left out.", pronunciation: "en-TYR", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "events", definition: "Things that happen, especially important occasions.", pronunciation: "i-VENTS", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "expect", definition: "To think that something will happen.", pronunciation: "ek-SPEKT", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "famine", definition: "A severe shortage of food in a region.", pronunciation: "FAM-in", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "fright", definition: "A sudden feeling of fear or shock.", pronunciation: "fryt", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "frolic", definition: "To play and move around cheerfully.", pronunciation: "FROL-ik", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "gravel", definition: "Small loose stones used on paths and roads.", pronunciation: "GRAV-ul", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "greedy", definition: "Wanting more food, money or possessions than is needed.", pronunciation: "GREE-dee", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "handle", definition: "The part of an object held to use it; to deal with a situation.", pronunciation: "HAN-dul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "health", definition: "The condition of the body and mind; being free from illness.", pronunciation: "helth", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "helmet", definition: "A hard protective covering worn on the head.", pronunciation: "HEL-met", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "horror", definition: "An intense feeling of fear, shock, or disgust.", pronunciation: "HOR-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "jumble", definition: "A confused mixture; to mix things together in disorder.", pronunciation: "JUM-bul", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "lively", definition: "Full of energy and enthusiasm.", pronunciation: "LYV-lee", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "lonely", definition: "Sad because of having no friends or company.", pronunciation: "LOHN-lee", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "manner", definition: "The way something is done; polite social behaviour.", pronunciation: "MAN-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "marvel", definition: "To be filled with wonder; something wonderful.", pronunciation: "MAR-vul", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "mascot", definition: "An animal or symbol chosen to bring good luck to a group.", pronunciation: "MAS-kot", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "matter", definition: "A subject or situation; to be important; physical substance.", pronunciation: "MAT-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "member", definition: "A person who belongs to a group or organisation.", pronunciation: "MEM-ber", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "mellow", definition: "Relaxed and calm; soft and rich in colour or taste.", pronunciation: "MEL-oh", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "melody", definition: "A sequence of musical notes forming a tune.", pronunciation: "MEL-uh-dee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "mighty", definition: "Very powerful or strong.", pronunciation: "MY-tee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "mingle", definition: "To mix with others; to chat socially.", pronunciation: "MING-ul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "mobile", definition: "Able to move freely; a mobile phone.", pronunciation: "MOH-bul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "moving", definition: "Changing position; causing strong emotion.", pronunciation: "MOOV-ing", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "muscle", definition: "A tissue in the body that contracts to produce movement.", pronunciation: "MUS-ul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "nimble", definition: "Quick and light in movement; clever.", pronunciation: "NIM-bul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "noodle", definition: "A long thin strip of pasta used in soups and Asian cooking.", pronunciation: "NOO-dul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "parent", definition: "A mother or father.", pronunciation: "PAIR-ent", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "people", definition: "Human beings; persons.", pronunciation: "PEE-pul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "person", definition: "An individual human being.", pronunciation: "PUR-sun", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "planet", definition: "A large round body in space that orbits a star.", pronunciation: "PLAN-it", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "pocket", definition: "A small bag sewn into clothing; to put something away.", pronunciation: "POK-it", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "ponder", definition: "To think carefully and at length about something.", pronunciation: "PON-der", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "possum", definition: "A small nocturnal marsupial native to Australia.", pronunciation: "POS-um", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "random", definition: "Done without a fixed pattern or plan.", pronunciation: "RAN-dum", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "ransom", definition: "Money demanded for releasing a captive.", pronunciation: "RAN-sum", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "render", definition: "To cause something to be; to provide a service.", pronunciation: "REN-der", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "rescue", definition: "To save someone from danger or difficulty.", pronunciation: "RES-kyoo", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "review", definition: "To examine again; a written opinion of a book or film.", pronunciation: "ri-VYOO", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "rising", definition: "Moving upward; increasing in amount.", pronunciation: "RY-zing", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "rocket", definition: "A vehicle propelled by expelled gas; to move very fast.", pronunciation: "ROK-it", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "rotate", definition: "To turn around a central point.", pronunciation: "roh-TAYT", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "rubber", definition: "An eraser; an elastic material made from latex.", pronunciation: "RUB-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "saddle", definition: "A seat on a horse or bicycle; to burden someone.", pronunciation: "SAD-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "sample", definition: "A small part taken to represent the whole.", pronunciation: "SAM-pul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "scarce", definition: "Not enough to meet demand; rare.", pronunciation: "skairs", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "secret", definition: "Something known only to a few people.", pronunciation: "SEE-krit", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "seldom", definition: "Not often; rarely.", pronunciation: "SEL-dum", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "series", definition: "A number of related things or events in order.", pronunciation: "SEER-eez", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "severe", definition: "Very harsh or extreme.", pronunciation: "si-VEER", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "sheila", definition: "Australian informal term for a woman or girl.", pronunciation: "SHEE-luh", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "signal", definition: "A gesture or sound that conveys information.", pronunciation: "SIG-nul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "source", definition: "The place where something comes from or begins.", pronunciation: "sors", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "spoken", definition: "Said aloud; past participle of speak.", pronunciation: "SPOH-ken", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "sprout", definition: "To begin to grow; a type of small vegetable.", pronunciation: "sprowt", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "statue", definition: "A carved or cast figure of a person or animal.", pronunciation: "STACH-oo", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "stormy", definition: "Having a lot of strong wind and rain.", pronunciation: "STOR-mee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "street", definition: "A public road in a town or city.", pronunciation: "street", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "stripe", definition: "A long narrow band of colour different from the surrounding area.", pronunciation: "stryp", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "tablet", definition: "A small flat pill; a portable touchscreen computer.", pronunciation: "TAB-let", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "talent", definition: "A natural ability or skill.", pronunciation: "TAL-ent", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "tender", definition: "Gentle and kind; soft and easy to chew.", pronunciation: "TEN-der", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "thrive", definition: "To grow or develop well and vigorously.", pronunciation: "thryv", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "ticket", definition: "A piece of paper giving the right to enter or travel.", pronunciation: "TIK-it", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "trance", definition: "A half-conscious dreamy state.", pronunciation: "trans", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "trophy", definition: "A prize given for winning a competition.", pronunciation: "TROH-fee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "tucker", definition: "Australian informal word for food.", pronunciation: "TUK-er", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "tumble", definition: "To fall suddenly and clumsily; an acrobatic roll.", pronunciation: "TUM-bul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "tundra", definition: "A vast treeless Arctic plain where the ground is mostly frozen.", pronunciation: "TUN-druh", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "unlike", definition: "Different from; in contrast to.", pronunciation: "un-LYK", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "update", definition: "To make something more modern; newly added information.", pronunciation: "UP-dayt", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "urgent", definition: "Requiring immediate attention or action.", pronunciation: "UR-jent", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "wisdom", definition: "The ability to make good judgements based on experience.", pronunciation: "WIZ-dum", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "worker", definition: "A person who works, especially with their hands.", pronunciation: "WUR-ker", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "wrench", definition: "A tool for gripping and turning; to twist suddenly.", pronunciation: "rench", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "across", definition: "From one side to the other; on the other side of.", pronunciation: "a-KROS", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "agenda", definition: "A list of items to be discussed or done.", pronunciation: "a-JEN-da", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "almond", definition: "A type of nut that grows on trees, often used in cooking.", pronunciation: "AH-mond", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "answer", definition: "A response to a question or solution to a problem.", pronunciation: "AN-ser", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "antler", definition: "The branched horn of a deer or similar animal.", pronunciation: "ANT-ler", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "arcade", definition: "A covered passageway; a place with video games.", pronunciation: "ar-KAYD", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "arctic", definition: "Relating to the region around the North Pole; extremely cold.", pronunciation: "ARK-tik", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "armour", definition: "Protective covering worn in battle.", pronunciation: "AR-mer", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "arrest", definition: "To seize someone by authority of law.", pronunciation: "a-REST", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "asleep", definition: "In a state of sleep.", pronunciation: "a-SLEEP", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "author", definition: "A person who writes books or articles.", pronunciation: "AW-ther", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "avenue", definition: "A wide street or road; a way of approaching something.", pronunciation: "AV-en-yoo", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "baboon", definition: "A large monkey with a dog-like face found in Africa.", pronunciation: "ba-BOON", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "bamboo", definition: "A giant tropical grass with hollow woody stems.", pronunciation: "bam-BOO", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "banana", definition: "A long curved yellow fruit.", pronunciation: "ba-NAH-na", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "barely", definition: "Only just; almost not.", pronunciation: "BARE-lee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "beauty", definition: "A combination of qualities that pleases the senses.", pronunciation: "BYOO-tee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "belief", definition: "Something you accept as true; trust or confidence.", pronunciation: "be-LEEF", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "bishop", definition: "A senior Christian priest; a chess piece.", pronunciation: "BISH-op", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "bitter", definition: "Having a sharp, unpleasant taste; feeling angry or upset.", pronunciation: "BIT-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "bleach", definition: "A chemical used to whiten or disinfect things.", pronunciation: "bleech", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "blonde", definition: "Having light golden hair; a person with fair hair.", pronunciation: "blond", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "botany", definition: "The scientific study of plants.", pronunciation: "BOT-a-nee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "bought", definition: "Past tense of buy; obtained by paying money.", pronunciation: "bawt", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "branch", definition: "A part of a tree growing from the trunk; a division of something.", pronunciation: "branch", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "breath", definition: "Air taken into or sent out of the lungs.", pronunciation: "breth", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "bridge", definition: "A structure built to cross a river or gap.", pronunciation: "brij", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "bronze", definition: "A brown metal; third place in a competition.", pronunciation: "bronz", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "brutal", definition: "Savage and violent; very harsh or hard.", pronunciation: "BROO-tal", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "burden", definition: "A heavy load; something difficult to carry or deal with.", pronunciation: "BUR-den", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "carpet", definition: "A thick fabric floor covering.", pronunciation: "KAR-pet", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "carrot", definition: "An orange root vegetable.", pronunciation: "KA-rot", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "caught", definition: "Past tense of catch; seized or captured.", pronunciation: "kawt", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "cereal", definition: "A grain plant used as food; a breakfast food.", pronunciation: "SEER-ee-al", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "chorus", definition: "A group of singers; a repeated part of a song.", pronunciation: "KOR-us", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "chrome", definition: "A shiny silver metal used for coating surfaces.", pronunciation: "krome", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "clover", definition: "A small plant with three-lobed leaves, common in lawns.", pronunciation: "KLOH-ver", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "combat", definition: "Fighting between armed forces; to fight against.", pronunciation: "KOM-bat", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "comedy", definition: "Entertainment that makes people laugh.", pronunciation: "KOM-e-dee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "crafty", definition: "Clever at achieving things by indirect methods; skilled.", pronunciation: "KRAF-tee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "creamy", definition: "Having a rich, smooth texture like cream.", pronunciation: "KREE-mee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "creepy", definition: "Causing an unpleasant feeling of fear.", pronunciation: "KREE-pee", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "cuddle", definition: "To hold someone close in a loving way.", pronunciation: "KUD-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "dazzle", definition: "To impress greatly; to blind with a bright light.", pronunciation: "DAZ-ul", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "decade", definition: "A period of ten years.", pronunciation: "DEK-ayd", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "decent", definition: "Of a good standard; acceptable or appropriate.", pronunciation: "DEE-sent", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "devour", definition: "To eat something greedily and quickly.", pronunciation: "de-VOW-er", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "dimple", definition: "A small dent in the cheek when smiling.", pronunciation: "DIM-pul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "donate", definition: "To give something, especially to a charity.", pronunciation: "doh-NAYT", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "emerge", definition: "To come out from a hidden place; to become known.", pronunciation: "e-MURJ", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "employ", definition: "To give work to someone; to use something.", pronunciation: "em-PLOY", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "energy", definition: "The power to do work or be active.", pronunciation: "EN-er-jee", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "expose", definition: "To uncover or reveal; to leave unprotected.", pronunciation: "eks-POHZ", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "feisty", definition: "Lively, active and spirited; ready to fight.", pronunciation: "FY-stee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "fierce", definition: "Very strong or violent; having a strong will.", pronunciation: "feers", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "figure", definition: "A shape or outline; a number; an important person.", pronunciation: "FIG-yer", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "filter", definition: "A device that removes unwanted substances.", pronunciation: "FIL-ter", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "flight", definition: "The action of flying; a journey by aeroplane.", pronunciation: "flyt", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "fluffy", definition: "Light and soft like fluff or feathers.", pronunciation: "FLUF-ee", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "frenzy", definition: "A state of wild excitement or uncontrolled activity.", pronunciation: "FREN-zee", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "frosty", definition: "Very cold with frost; unfriendly in manner.", pronunciation: "FROS-tee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "fumble", definition: "To handle something clumsily.", pronunciation: "FUM-bul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "fungus", definition: "A living organism like mushrooms or mould.", pronunciation: "FUNG-gus", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "galaxy", definition: "A huge system of stars in outer space.", pronunciation: "GAL-ak-see", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "gallop", definition: "The fastest pace of a horse; to run very fast.", pronunciation: "GAL-op", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "garlic", definition: "A plant with a strong smell used to flavour food.", pronunciation: "GAR-lik", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "giggle", definition: "To laugh in a light, silly way.", pronunciation: "GIG-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "ginger", definition: "A spicy root used in cooking; a reddish-orange colour.", pronunciation: "JIN-jer", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "goblin", definition: "A mischievous ugly creature from folklore.", pronunciation: "GOB-lin", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "grumpy", definition: "Bad-tempered and unhappy.", pronunciation: "GRUM-pee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "guilty", definition: "Responsible for breaking a rule or law; feeling ashamed.", pronunciation: "GIL-tee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "hammer", definition: "A tool for hitting nails; to hit repeatedly.", pronunciation: "HAM-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "hazard", definition: "A danger or risk.", pronunciation: "HAZ-erd", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "heroic", definition: "Having the qualities of a hero; very brave.", pronunciation: "he-ROH-ik", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "joyful", definition: "Feeling or causing great happiness.", pronunciation: "JOY-ful", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "jumper", definition: "A warm knitted top; in Australia, a sweater.", pronunciation: "JUM-per", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "leader", definition: "A person who leads or commands a group.", pronunciation: "LEE-der", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "litter", definition: "Rubbish left in a public place; a group of baby animals born together.", pronunciation: "LIT-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "locate", definition: "To find the position of something.", pronunciation: "loh-KAYT", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "magnet", definition: "An object that attracts iron and steel.", pronunciation: "MAG-net", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "modest", definition: "Not boasting about yourself; not large or showy.", pronunciation: "MOD-est", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "mostly", definition: "For the most part; mainly.", pronunciation: "MOHST-lee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "muffin", definition: "A small round cake or bread roll.", pronunciation: "MUF-in", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "mussel", definition: "A shellfish with a dark hinged shell.", pronunciation: "MUS-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "nearby", definition: "Not far away; close in distance.", pronunciation: "NEER-by", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "notion", definition: "An idea or belief about something.", pronunciation: "NOH-shun", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "online", definition: "Connected to the internet; available via computer.", pronunciation: "ON-lyne", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "option", definition: "A choice between two or more things.", pronunciation: "OP-shun", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "pebble", definition: "A small smooth rounded stone.", pronunciation: "PEB-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "pigeon", definition: "A grey bird often seen in cities.", pronunciation: "PIJ-un", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "pillar", definition: "A tall vertical column used as a support.", pronunciation: "PIL-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "plunge", definition: "To jump or dive quickly; to push something suddenly.", pronunciation: "plunj", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "pollen", definition: "A fine powder produced by flowers for fertilisation.", pronunciation: "POL-en", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "prawns", definition: "Small shellfish with long tails, popular in Australian cooking.", pronunciation: "prawns", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "quartz", definition: "A hard mineral found in rocks, often used in watches.", pronunciation: "kwarts", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "quench", definition: "To satisfy thirst by drinking; to put out a fire.", pronunciation: "kwench", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "racket", definition: "A bat used in tennis; a loud noise; a dishonest scheme.", pronunciation: "RAK-et", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "radish", definition: "A small red or white root vegetable with a peppery taste.", pronunciation: "RAD-ish", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "recipe", definition: "Instructions for making a dish of food.", pronunciation: "RES-e-pee", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "reckon", definition: "To think or believe; to calculate.", pronunciation: "REK-un", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "region", definition: "A large area of land with particular characteristics.", pronunciation: "REE-jun", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "reward", definition: "Something given for good work or behaviour.", pronunciation: "re-WORD", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "ripple", definition: "A small wave on water; a spreading effect.", pronunciation: "RIP-ul", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "robust", definition: "Strong and healthy; able to withstand difficult conditions.", pronunciation: "roh-BUST", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "rumble", definition: "A continuous deep rolling sound.", pronunciation: "RUM-bul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "runway", definition: "A strip of ground where aircraft take off and land.", pronunciation: "RUN-way", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "rustle", definition: "A soft crackling sound like leaves in the wind.", pronunciation: "RUS-ul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "salmon", definition: "A large pink fish that lives in rivers and the sea.", pronunciation: "SAM-un", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "savage", definition: "Fierce, violent and uncontrolled.", pronunciation: "SAV-ij", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "savour", definition: "To enjoy the taste or smell of something slowly.", pronunciation: "SAY-ver", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "sermon", definition: "A talk on a religious or moral subject.", pronunciation: "SUR-mun", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "shiver", definition: "To shake with cold or fear.", pronunciation: "SHIV-er", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "sizzle", definition: "To make a hissing sound when cooking; to be very hot.", pronunciation: "SIZ-ul", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "sleepy", definition: "Feeling the need to sleep; quiet and without much activity.", pronunciation: "SLEE-pee", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "snappy", definition: "Quick and clever; irritably impatient.", pronunciation: "SNAP-ee", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "snooze", definition: "To sleep lightly for a short time.", pronunciation: "snooz", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "soccer", definition: "A football game played with a round ball by two teams of eleven.", pronunciation: "SOK-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "soften", definition: "To become or make less hard, strict, or strong.", pronunciation: "SOF-en", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "sporty", definition: "Fond of sport; looking suitable for sport.", pronunciation: "SPORT-ee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "spread", definition: "To open out or stretch over a surface.", pronunciation: "spred", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "squeal", definition: "A long high-pitched cry or sound.", pronunciation: "skweel", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "static", definition: "Not moving or changing; electrical noise or interference.", pronunciation: "STAT-ik", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "steady", definition: "Firmly fixed; regular and even; not changing.", pronunciation: "STED-ee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "stroll", definition: "A slow relaxed walk.", pronunciation: "strohl", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "sunset", definition: "The time when the sun goes down in the evening.", pronunciation: "SUN-set", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "surfer", definition: "A person who rides waves on a surfboard.", pronunciation: "SUR-fer", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "swerve", definition: "To change direction suddenly to avoid something.", pronunciation: "swurv", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "tangle", definition: "A twisted, knotted mass; to become twisted together.", pronunciation: "TANG-gul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "tennis", definition: "A sport played with rackets and a ball on a court.", pronunciation: "TEN-is", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "timely", definition: "Done or happening at a good or suitable time.", pronunciation: "TYM-lee", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "tinsel", definition: "Thin strips of shiny material used as decoration.", pronunciation: "TIN-sul", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "tremor", definition: "A slight shaking movement; a small earthquake.", pronunciation: "TREM-er", hasRepeatingLetters: true, hasRareLetters: false },
  { word: "tricky", definition: "Difficult to deal with; using clever tricks.", pronunciation: "TRIK-ee", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "turnip", definition: "A round white root vegetable.", pronunciation: "TUR-nip", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "uneven", definition: "Not level or smooth; not regular or equal.", pronunciation: "un-EE-ven", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "unfair", definition: "Not treating everyone equally; unjust.", pronunciation: "un-FAIR", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "united", definition: "Joined together as one; working together.", pronunciation: "yoo-NY-ted", hasRepeatingLetters: false, hasRareLetters: false },
  { word: "velvet", definition: "A soft fabric with a thick short pile.", pronunciation: "VEL-vet", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "waddle", definition: "To walk with short steps swinging from side to side, like a duck.", pronunciation: "WOD-ul", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "warmly", definition: "In a friendly and enthusiastic way; with warmth.", pronunciation: "WORM-lee", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "wicker", definition: "Thin flexible twigs woven together to make furniture or baskets.", pronunciation: "WIK-er", hasRepeatingLetters: false, hasRareLetters: true },
  { word: "wiggle", definition: "To move from side to side with small quick movements.", pronunciation: "WIG-ul", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "willow", definition: "A tree with long drooping branches that grows near water.", pronunciation: "WIL-oh", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "woolly", definition: "Made of or resembling wool; covered with wool.", pronunciation: "WOOL-ee", hasRepeatingLetters: true, hasRareLetters: true },
  { word: "yearly", definition: "Happening once a year; every year.", pronunciation: "YEER-lee", hasRepeatingLetters: true, hasRareLetters: false },
];
